<div class='div text-center  p-3' style="width:600px;margin-left:300px;border:2px solid lightgreen">
<form action="../product/productadd" method="post">
    <h1>Add Product's</h1>
    <label>Product Id</label>
    <input type="number" name="id" class="form-control">
    <br>
    <label>Product Name</label>
    <input type="text" name="name" class="form-control">
    <br>
    <label>Product Quantity</label>
    <input type="number" name="qty" class="form-control">
    <br>
    <label>Product Price</label>
    <input type="number" name="price" class="form-control">
    <br>
    <label>Product Description</label>
    <input type="text" name="desc" class="form-control">
    <br><br>
    <input type="submit" value="submit" class='btn btn-primary'>
    <a href="../product/productview" class="btn btn-primary">View Products</a>
</form>
</div>

