<table class="table table-striped table-bordered">
    <caption>table shows product details</caption>
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>qty</th>
            <th>price</th>
            <th>Action <a href='../product' class='btn btn-primary'>Add Product</a></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $value) {
            echo "<tr><td>$value->id</td><td>$value->name</td><td>$value->desc</td><td>$value->qty</td><td>$value->price
            </td><td><a href='../product/update?id=$value->id' class='btn btn-warning'>Update</a>
            <a href='../product/delete?id=$value->id' class='btn btn-danger'>Delete</a></td></tr>";
        }
        ?>
    </tbody>

</table>
