<div class='div text-center  p-3' style="width:600px;margin-left:300px;border:2px solid lightgreen">
<form action="../product/productupdate" method="post">
    <h1>Update Product's</h1>
    <label>Product Id</label>
    <input type="number" name="id"   class="form-control" value='<?php echo $data->id;?>'>
    <br>
    <label>Product Name</label>
    <input type="text" name="name" class="form-control" value='<?php echo $data->name;?>'>
    <br>
    <label>Product Quantity</label>
    <input type="number" name="qty" class="form-control" value='<?php echo $data->qty;?>'>
    <br>
    <label>Product Price</label>
    <input type="number" name="price" class="form-control" value='<?php echo $data->price;?>'>
    <br>
    <label>Product Description</label>
    <input type="text" name="desc" class="form-control" value='<?php echo $data->desc;?>'>
    <br><br>
    <input type="submit" value="Update" class='btn btn-primary'>
</form>
</div>
